CREATE OR REPLACE SPOTIFY_DB.SPOTIFY_PIPES.ALBUM_PIPE
AUTO_INGEST = TRUE
COPY INTO SPOTIFY_DB.PUBLIC.tblALBUM
FROM @SPOTIFY_DB.EXTERNAL_STAGES.ALBUM_STAGE;

CREATE OR REPLACE SPOTIFY_DB.SPOTIFY_PIPES.ARTIST_PIPE
AUTO_INGEST = TRUE
COPY INTO SPOTIFY_DB.PUBLIC.tblARTIST
FROM @SPOTIFY_DB.EXTERNAL_STAGES.ARTIST_STAGE;

CREATE OR REPLACE SPOTIFY_DB.SPOTIFY_PIPES.SONGS_PIPE
AUTO_INGEST = TRUE
COPY INTO SPOTIFY_DB.PUBLIC.tblSONGS
FROM @SPOTIFY_DB.EXTERNAL_STAGES.SONGS_STAGE;